### ISSUE TITLE
design the database

### ISSUE THREAD

**Issue by csySally** [LiliLiu09/CITS5505_AgileWebProject2#18]
**Need a meeting together**

- Design the database structure before 1st May (Wednesday)
- Make sure everybody can catch up with _flask lab_ (week 8 ) content related to database 
- Need to assign someone to build the database _TBC_
- Can use [https://www.drawio.com](url) for designing. This can be put in our **deliverable** of back-end

**Comment by joshjin11** [comment]
Got it, Sally. I'll start looking into the database design

**Comment by Dave-114-P** [comment]
I see, now working on it

**Comment by csySally** [comment]
@LiliLiu09 @Dave-114-P @joshjin11 we will have a team meeting before Wednesday and please share your idea about the structure of database. then we'll separate the tasks including:

1. draw the final design using the tool i mentioned above
2. design the database, use **SQLAlchemy** from Flask in `model.py`

**Comment by LiliLiu09** [comment]
let's talk about it on tuesday night
