### ISSUE TITLE
static register

### ISSUE THREAD

**Issue by csySally** [LiliLiu09/CITS5505_AgileWebProject2#2]
**Figma Design now is available for this two pages:**
https://www.figma.com/file/SqRgaZQaXlgRzC7S6k2ZZA/React-%2F-Drifter?type=design&node-id=0-1&mode=design

1. Basically it's exactly the same as login page.
2. Please @joshjin11 work in your own branch and ask for a pull request to merge into the main one. For details read README.md
3. @csySally will do the de-duplication work after both login and register pages are done.

**Comment by joshjin11** [comment]
Got it, I'll start working on the tasks in my branch. Thanks for the heads-up about the Figma designs and the de-duplication process with @csySally

**Comment by csySally** [comment]
> Got it, I'll start working on the tasks in my branch. Thanks for the heads-up about the Figma designs and the de-duplication process with @csySally

no worries, any questions please let me know without hesitation!
