### ISSUE TITLE
block default commits

### ISSUE THREAD

**Issue by csySally** [LiliLiu09/CITS5505_AgileWebProject2#29]
1. stop the default commit of add notes (now can click 'next' button with empty notes, should stop that)
2. stop the default commit of add labels (now can click 'OK!' button to submit the labels with empty labels, should stop that, user should at least enter one label)

**Comment by csySally** [comment]
add me as a reviewer when you pull request

**Comment by Dave-114-P** [comment]
<img width="464" alt="image" src="https://github.com/LiliLiu09/CITS5505_AgileWebProject2/assets/127728293/efc89544-cb87-439d-ac1f-7bd96929b0bf">
picture for the close btn
