### ISSUE TITLE
create links to logo for each page

### ISSUE THREAD

**Issue by csySally** [LiliLiu09/CITS5505_AgileWebProject2#57]
<img width="939" alt="image" src="https://github.com/LiliLiu09/CITS5505_AgileWebProject2/assets/100677723/556f24a0-bf20-407a-aa48-98311c24f4cf">
Each page should link to index.html except login & register.

Please work on your own branch. If have any questions or need help, please tag me using the labels on the right side or comment here.

**Comment by joshjin11** [comment]
got it
