### ISSUE TITLE
bug fix for static pages

### ISSUE THREAD

**Issue by csySally** [LiliLiu09/CITS5505_AgileWebProject2#59]
1. register page has a bug
![image](https://github.com/LiliLiu09/CITS5505_AgileWebProject2/assets/100677723/b1daaec3-08f3-4d2f-9066-425369add9ab)
2. check inbox has a bug
<img width="639" alt="image" src="https://github.com/LiliLiu09/CITS5505_AgileWebProject2/assets/100677723/ad37cd0e-7aa0-4997-8042-f9a5f53ba84c">

**Comment by joshjin11** [comment]
thanks sally
