### ISSUE TITLE
general setup of flask and sqlite

### ISSUE THREAD

**Issue by csySally** [LiliLiu09/CITS5505_AgileWebProject2#6]
1. Please work on the specific branch.
2. Follow the folder structure.
3. Commit more! Update regularly!
4. Create more issues related to the details @Dave-114-P

**Comment by Dave-114-P** [comment]
Done: 
1. Adding Flask and a sqlite3 testing 
Todo: 
1. Design tables for user information, note content.
2. Flask login and session logics.
3. POST and GET action testing
4. Queries to acquire note content based on user.
5. Interfacing with front-end teammates

**Comment by csySally** [comment]
> Done:
> 
> 1. Adding Flask and a sqlite3 testing
>    Todo:
> 2. Design tables for user information, note content.
> 3. Flask login and session logics.
> 4. POST and GET action testing
> 5. Queries to acquire note content based on user.
> 6. Interfacing with front-end teammates

Good to know! We'll start designing the database and API next week after everyone's mid-term tests and assignments done.

**Comment by Dave-114-P** [comment]
Done:
1. Adding Flask and a sqlite3 testing
Todo:
1. Design tables for user information, note content.
2. Flask login and session logics.
3. POST and GET action testing
4. Queries to acquire note content based on user.
5. Interfacing with front-end teammates
